requirejs.config({
  baseUrl: './js',
  waitSeconds: 30,
  paths: {
    'jquery': 'jquery.min',
    'angular': 'angular.min',
    'ngInfiniteScroll': 'ng-infinite-scroll.min',
    'bxslider': 'jquery.bxslider',
    'flexslider': 'jquery.flexslider',
    'flipster': 'jquery.flipster.min',
    'mCustomScrollBar': 'jquery.mCustomScrollbar.min',
    'main-themes': 'main-themes',
    'website_login': 'website_login',
    'additional-methods': 'additional-methods.min',
    'jquery-validate': 'jquery.validate.min',
    'intlTelInput': 'intlTelInput',
    'nicEdit': 'nicEdit',
    'shapeshift': 'jquery.shapeshift',
    'ngShapeshift': 'angular-shapeshift',
    'bootstrap': 'bootstrap.min',
    'cropper': 'cropper',
    'main': 'main',
    'main-crop': 'main-crop',
    'colpick': 'colpick',
    'customFramework': 'customFrameworkLive',
    'font_Color': 'font_ColorLive',
    'jquery-ui': 'jquery-ui',
    'mCustomScrollbar-concat': 'jquery.mCustomScrollbar.concat.min',
    'chosen': 'chosen.jquery',
    'ImageSelect': 'ImageSelect.jquery',
    'pramukhime': 'pramukhime',
    'pramukhindic': 'pramukhindic',
    'pramukhime-common': 'pramukhime-common',
    'main-panel': 'main-panel',
    'main-catalogue': 'main-catalogue',
    'publish': 'publishJS',
    'html2canvas': 'html2canvas'
  },
  shim: {
    'jquery': {
      exports: '$'
    },
    'angular': {
      exports: 'angular'
    },
    'bxslider': ['jquery'],
    'flexslider': ['jquery'],
    'flipster': ['jquery'],
    'mCustomScrollBar': ['jquery'],
    'ngInfiniteScroll': ['angular'],
    'website_login': ['jquery'],
    'jquery-validate': ['jquery'],
    'additional-methods': ['jquery', 'jquery-validate'],
    'intlTelInput': ['jquery'],
    'shapeshift': ['jquery', 'jquery-ui'],
    'ngShapeshift': ['shapeshift', 'angular'],
    'bootstrap': ['jquery'],
    'cropper': ['jquery'],
    'main': ['jquery', 'cropper'],
    'main-crop': ['jquery', 'cropper'],
    'colpick': ['jquery'],
    'customFramework': ['jquery', 'shapeshift', 'mCustomScrollbar-concat'],
    'font_Color': ['jquery', 'colpick'],
    'jquery-ui': ['jquery'],
    'mCustomScrollbar-concat': ['jquery'],
    'chosen': ['jquery'],
    'ImageSelect': ['jquery'],
    'pramukhime': ['jquery'],
    'pramukhindic': ['jquery', 'pramukhime'],
    'pramukhime-common': ['jquery', 'pramukhime', 'pramukhindic'],
    'html2canvas': ['jquery']
  }
});