<?php require_once('website_header.php');?>

<div class="brdcrm">
  <div class="big-cont mt0">
    <div class="crm"> <a href="#">Home</a><span> >> </span><a href="#" class="active-crum">Terms of Service</a> </div>
  </div>
</div>
<div class="big-cont mt0 suc"> 
  <!--<ul class="pagi fr" >
        <li><a href="#"><i class="fa fa- fa-angle-double-left"></i></a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#"><i class="fa  fa-angle-double-right"></i></a></li>
    </ul>-->
  
  <h3 class="term-head">1. PREMISE </h3>
  <div class="term-desc"> The terms as hereinafter appearing, shall govern use of the product website Instappy.com including, but not limited to, the subscription plans promoted on the product website, the privacy policy, the creation, modification and the downloading, activation, publishing, purchase, monetary transaction, communication, emails and other instructions. The content(s), services, and other features of the application builder product website Instappy.com hereby referred to as INSTAPPY.COM, available at or through the Instappy.com website offered to the customers/you (collectively “use of services” or “services”). <div class="space"></div>
    These terms, subscription plans, the privacy policy, and the downloading, activation and other instructions are collectively referred to as “these Terms” or “the Term of Services” or “this Agreement”. The service is owned by Pulp Strategy Technologies Pvt. Ltd. and operated by Pulp Strategy Communication Pvt Limited having business offices at Plot no: 48, 2nd floor, Okhla Industrial Estate, Phase 3, New Delhi, 110020, India and 111 North Market Street Suite 300,
	San Jose, CA 95113, USA and (“Instappy.com”, “We”, “Pulp Strategy”) hereby referred to as “Pulp Strategy”. The software based service is offered subject to your acceptance without modification of all the agreement and all other operating rules, policies (including, without limitation, Instappy.com’ Privacy Policy) and procedures that may be published from time to time on the Instappy.com website by Pulp Strategy.  Please read this agreement carefully before accessing or using the service. By accessing or using any part of the service, it is hereby agreed that you agree to the terms as herein appearing.<div class="space"></div>
    Instappy.com is a digital platform whereby you create, build, prepare, and enable publishing of mobile applications to popular mobile app stores. You can download, install, activate and make use of the service and make use of or avail other services provided by Pulp Strategy via Instappy.com, by registering yourself on this website and following the set process including, but not limited to, the terms of service of Instappy.com. <div class="space"></div>
    BY REGISTERING, LOGGING IN,  DOWNLOADING, INSTALLING, ACTIVATING, CREATING, BUILDING LAUNCHING, OR TAKING ANY ACTION OR USING INSTAPPY.COM, YOU ARE AGREEING TO BE BOUND BY THESE TERMS.  YOU MUST GO THROUGH THESE TERMS (INCLUDING SUBSCRIPTION PLANS, PRIVACY POLICY, ANY INSTRUCTIONS AND OTHER RELATED TERMS & CONDITIONS AS PROVIDED ON THE WEBSITE) BEFORE REGISTERING, LOGGING IN, DOWNLOADING, INSTALLING, ACTIVATING OR OTHERWISE MAKING USE OF SERVICES. <div class="space"></div>
    These terms are enforceable against you or any entity that has subscribed to INSTAPPY.COM or otherwise made use of services. If you do not agree, do not subscribe or otherwise make use of services. Pulp Strategy reserves the right to change these terms at any time without any prior intimation. You are advised that any amendment to these terms or policies incorporated herein will only be notified on/through the website or accessible links and you agree to read these terms before making any subscription or otherwise making use of services. The revised version/ terms shall be effective from the time the same is made publically assessable on /through any link on the website.<div class="space"></div>
    Pulp Strategy permits you to subscribe to INSTAPPY.COM or otherwise make use of services only in accordance with these terms. Use of third party items /platform in relation to the use of INSTAPPY.COM may be subject to terms & conditions of such third party. You will also be required to accept and follow such terms & conditions. Such terms & conditions of third party will supersede all or portions of these terms in the event of a conflict. </div>
  <h3 class="term-head">2. TERMINOLOGY </h3>
  <div class="term-desc"> Following words used in this presents/terms have the following meaning: <div class="space"></div>
    “Device” denotes the devices on which support software/ applications will be installed, tested or run; <div class="space"></div>
    “Otherwise made use of services” or “otherwise make use of services” shall mean use or subscription of any other services including registering, logging in or availing free trial services of INSTAPPY.COM <div class="space"></div>
    “Pulp Strategy” denotes the company namely PULP STRATEGY TECHNOLOGIES PRIVATE LIMITED, and PULP STRATEGY COMMUNICATIONS PRIVATE LIMITED company(S) incorporated and registered under the (Indian) Companies Act, 1956, having its business offices at Plot no: 48, 2nd floor, Okhla Industrial Estate, Phase 3, New Delhi, 110020, India and 111 North Market Street Suite 300,San Jose, CA 95113, USA. <div class="space"></div>
    “SERVER / HOSTING” denotes the server owned, utilised, leased and or commissioned for facilitating the Instappy.com  services; <div class="space"></div>
    “Instappy.com services” or “services” denotes the services provided by Pulp Strategy through the website including subscription of INSTAPPY.COM and other allied or ancillary services as is informed through website Instappy.com. <div class="space"></div>
    “Subscriber” denotes the person, entity or organisation who/which subscribes to INSTAPPY.COM or otherwise makes use of services with or without paid subscription; <div class="space"></div>
    “Subscription fee” shall mean the fee/amount payable by the subscriber for subscribing INSTAPPY.COM for the subscription period; <div class="space"></div>
    “Subscribed to INSTAPPY.COM” or “subscription of INSTAPPY.COM” or “subscription”  or “subscribe” shall mean downloading, installation, creation, activating, or using INSTAPPY.COM after payment of subscription fee. <div class="space"></div>
    “Subscription period” means the period for which the INSTAPPY.COM services or other products are subscribed by the subscriber as per the duration of the subscription plan paid for; <div class="space"></div>
    “Third party offerings/platforms” or “third party services” shall mean the platform on which the services are registered, published and or linked to the services provided by Instappy.com. <div class="space"></div>
    “Website” means the website Instappy.com, through which subscriber can get access to and or subscribe to the services provided by INSTAPPY.COM or other products or otherwise make use of services; <div class="space"></div>
  </div>
  <h3 class="term-head">3. ELIGIBILITY </h3>
  <div class="term-desc"> YOU CAN SUBSCRIBE INSTAPPY.COM OR OTHERWISE MAKE USE OF SERIVCES ONLY WHEN YOU ARE ABLE TO FORM A LEGALLY BINDING CONTRACT UNDER INDIAN CONTRACT ACT, 1872. Thus you agree that: 
  	<ul class="roman">
    	<li>You are above 18 years of age;</li>
  		<li>You are a person of sound mind and not un-discharged insolvent;</li>
  		<li>You are otherwise not incompetent to contract within the meaning of Indian Contract Act, 1872. If you are subscribing INSTAPPY.COM or otherwise making use of services as a business entity, by accepting this agreement, you represent that such entity has sufficient authority under the applicable law to enter into this agreement and you are duly authorised by the business entity to accept this agreement and you have the authority to bind that business entity to this agreement.</li>
    </ul>
   <div class="space"></div>
   </div>
  <h3 class="term-head">4. REGISTRATION, INFORMATION AND COMMUNICATION</h3>
  <div class="term-desc"> In order to access services, you are required to register and open a personal account, providing your accurate information. You will be solely liable and responsible for all activities that occur under your account (including, but not limited to, any purchase of services made through your account). You acknowledge and agree that you are solely responsible for maintaining secrecy and confidentiality of your username and password and other information provided including payment details. Please note that you will be responsible for all activities that occur under your account (including, but not limited to, any purchase of the service made through your account) unless you notify us that your account has demonstrably been used by a third party without your consent. You are further responsible for maintaining the confidentiality of your access information and for ensuring that no third party accesses your account without your consent. Instappy.com cannot and will not be liable for any loss or damage arising from your failure to comply with these obligations. You will immediately notify Instappy.com of any unauthorised use of your account. The account will be created based upon the personal information you provide to us. <div class="space"></div>
    You further acknowledge and agree that while subscribing to INSTAPPY.COM or otherwise making use of services you will provide your true, accurate and complete information. You will also provide the correct billing address. You will be solely liable & responsible for providing incorrect and or incomplete information. You are also solely responsible to maintain and promptly update the information provided while subscribing or otherwise making use of services on the website to ensure that the information provided by you is true, accurate, current and complete at all times. You are prohibited from misrepresenting your identity or using identity of any other person while subscribing INSTAPPY.COM or otherwise making use of services. <div class="space"></div>
    If the provided information is untrue, inaccurate, not current or incomplete or Pulp Strategy has reasonable grounds to deduce that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this agreement, its reserves the right to indefinitely suspend or terminate or block your use or access to the website or use of INSTAPPY.COM in any manner whatsoever and further to cancel your subscription without refund or payment of any compensation to you. <div class="space"></div>
    You hereby acknowledge and accept that the website or INSTAPPY.COM will grant access to any person who has obtained your username and password in the same manner as it would have granted access to you and you are responsible for all activities conducted under your username and password. Pulp Strategy, its employees or associates will not be responsible in any manner for losses occurring from such breach of secrecy of your username and password. <div class="space"></div>
    You acknowledge and agree that you will keep yourself updated with all data, information and communication pertaining to you or the services used by you made available on INSTAPPY.COM or other services. You further agree that your use of the website/ INSTAPPY.COM or provision of any data or information including any correspondence (by email or otherwise) to or by Pulp Strategy is through electronic records and you consent to receive communication from Pulp Strategy via electronic records which will be deemed adequate service of notice. In addition to the electronic records and or communication, there may be telephonic communication and you consent to receive communication from Pulp Strategy via telephonic calls. <div class="space"></div>
  </div>
  <h3 class="term-head">5. SUBSCRIPTION/LICENSE</h3>
  <div class="term-desc"> Instappy.com has developed a digital platform which helps the customer / you to create and manage, through software owned and/or managed by Instappy.com customised and or personalised mobile applications for iOS and Android devices, and for other operating system that Instappy.com may decide to adopt in the future (the “Digital Platform”). Subject to the agreement, and upon payment to Instappy.com of applicable fees, Instappy.com grants the customer a worldwide revocable, non-exclusive, non-transferable license during the duration term of the agreement (the “Term”) to use the services and the Digital Platform in accordance with the plans / subscription duration. In order to continue to use the service(s) and thus the mobile application, the subscription will need to be renewed by you as per the applicable terms at the time of renewal at the cost applicable for the renewal of the services / subscription. <div class="space"></div>
    The website contains the description of services offered, the subscription plan containing duration terms, the applicable fee, technical assistance for using the services, if any, other special features and tools, if any and other relevant information of the services rendered through the digital platform. Pulp Strategy reserves its right to vary the content of each plan, including fees, duration terms, extension of services rendered etc. from time to time. Pulp Strategy may terminate a subscription plan anytime. Termination or variation of subscription plans by Pulp Strategy does not entitle you to any compensation. In particular, pricing specified in the plans relating mobile applications which, during the subscription cycle, exceed the given limit of data / space, then the customer has to pay the extra fees which will be informed by Instappy.com time to time to avoid discontinuation of services. The fees shall be applicable in the current, immediate or next billing cycle in accordance with Instappy.com instructions, save as otherwise agreed with the customer. Pulp Strategy reserves the right to set up a website’s dashboard where you can directly upgrade, renew the plan or modify personal account settings and information, or delete the personal account. All these features can be performed in accordance with these terms and with the instructions provided in the website and/or the dashboard. <div class="space"></div>
    When you subscribe, it means that INSTAPPY.COM is licensed and not sold. Subject to the terms & conditions as contained herein, this agreement grants you a personal, non-exclusive, non-transferable license that permits you and your authorised user to create, download, install, activate and use INSTAPPY.COM corresponding to the subscription fee paid. As part of the free trial, you may install and use one copy of your application created using INSTAPPY.COM on one device. <div class="space"></div>
    You may acquire subscription of INSTAPPY.COM on a term subscription basis or as part of a free trial, and your subscription /license rights set out above apply only for the time period for which you have paid the requisite subscription fees or for the time period authorised by Pulp Strategy for free trial. <div class="space"></div>
    These terms and the license granted herein do not imply any rights or entitlement to:
    <ul class="alphabet">
    	<li>future upgrades or updates of INSTAPPY.COM; or</li>
        <li>acquire any new or modified services.  Not withstanding the foregoing, INSTAPPY.COM may include functionality to automatically check for updates or upgrades, unless you configure INSTAPPY.COM to preclude the transmission or use of upgrades or updates. You hereby agree that Pulp Strategy may (but is not obligated to) make such updates or upgrades available to you from time-to-time. If Pulp Strategy makes any updates or upgrades to INSTAPPY.COM or services available to you, such updates or upgrades shall be subject to the payment of such additional fee, as Pulp Strategy may determine and to the terms and conditions of this agreement and such additional terms and conditions as may be provided. </li>
    </ul>
    The license does not grant you the right to sublicense or distribute INSTAPPY.COM. For information about obtaining the right to distribute INSTAPPY.COM, please contact Pulp Strategy. Except as expressly set forth in these terms, no license is granted and none shall be deemed granted by implication, estoppels or otherwise. In the event you are found sublicensing or distributing Instappy or the services provided by Instappy and or Pulp Strategy you are liable to pay damages as may be deemed fit by Pulp Strategy. <div class="space"></div>
  </div>
  <h3 class="term-head">6. Duration:</h3>
  <div class="term-desc"> Plan’s duration is twelve (12) month term or other different terms specified in the plans. Plan’s subscription is automatically renewable at its expiration date, for the same term, if you haven’t terminated the subscription prior its expiration date. You may terminate plan’s subscription renewal for the next term through the dashboard and in accordance with the instructions provided in the website from time to time. If you terminate your plan’s subscription, this means we won’t be able to refund you for early plan or agreement cancellation (see section 10 below). You can opt to upgrade your plan to any other plan that Instappy.com is currently offering for sale at any time during customer’s agreement term. Any plan downgrades will take effect when your next billing cycle begins. In the case of an upgrade, you will be charged for the difference in the cost of the two plans over the remainder of the original term. <div class="space"></div>
  </div>
  <h3 class="term-head">7. THIRD PARTY ACCOUNT</h3>
  <div class="term-desc"> Pulp Strategy may, from time to time, give you the possibility to register an account on Instappy.com and or services by logging with third party social networking sites (including, but not limited to, Facebook, Twitter, LinkedIn, Google etc.). As part of the functionality of the website, you may link your account with Third Party Accounts, by either: <div class="space"></div>
    <ul class="roman">
    	<li>providing your Third Party Account login information to Pulp Strategy through the website; or </li>
    	<li>allowing Pulp Strategy to access your Third Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third Party Account. You represent that you are entitled to disclose your Third Party Account login information to Pulp Strategy  and/or grant Pulp Strategy access to your Third Party Account (including, but not limited to, for use for the purposes described herein), without breach by you of any of the terms and conditions that govern your use of the applicable Third Party Account and without obligating Pulp Strategy to pay any fees or making Pulp Strategy subject to any usage limitations imposed by such third party service providers. By granting Pulp Strategy access to any Third Party Accounts, you understand that Pulp Strategy will access, make available and store (if applicable) any content that you have provided to and stored in your Third Party Account so that it is available on and through the website via your account. Depending on the Third Party Accounts you choose and subject to the privacy settings that you have set in such Third Party Accounts, personally identifiable information that you post to your Third Party Accounts will be available on and through your account on the website. Please note that if a Third Party Account or associated service becomes unavailable or Pulp Strategy’s access to such Third Party Account is terminated by the third party service provider, then Third Party Account content will no longer be available on and through the website. YOUR RELATIONSHIP WITH THE THIRD PARTY SERVICE PROVIDERS ASSOCIATED WITH YOUR THIRD PARTY ACCOUNTS IS GOVERNED SOLELY BY YOUR AGREEMENT(S) WITH SUCH THIRD PARTY SERVICE PROVIDERS. In such case, Pulp Strategy will not be responsible for any loss of content and damages </li>
    </ul>
  </div>
  <h3 class="term-head">8. FREE TRIAL VERSIONS </h3>
  <div class="term-desc"> Instappy.com services may provide a free trial including that of the application creation services. You may create, build, an application and download free trial version, which will be applicable for testing purposes on one device. This is available for trial purpose for the given period only. The trial period begins from the hour, day and date of your registration to create the application. The same may be downloaded free of cost and can be used for the period as may be prescribed by Pulp Strategy from time to time. Such free trial version may not contain the entire features as those are available with INSTAPPY.COM subscription, as the same shall only be for the trial purposes such that to create full confidence for the subscription. Such free trial version can be created and used from the website by following the given procedure. All the terms and conditions of this agreement shall be applicable to such free trial version(s) and you agree to adhere to the same. Free trial version may be withdrawn by Pulp Strategy any time, at its sole discretion, without any intimation to the general public/user. <div class="space"></div>
    FREE TRIAL IS "AS-IS," AND YOU BEAR THE RISK OF USING IT. PULP STRATEGY GIVES NO EXPRESS WARRANTIES, GUARANTEES OR CONDITIONS. TO THE EXTENT PERMITTED PULP STRATEGY EXCLUDES THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. <div class="space"></div>
    If free trial period has ended, and the payment cannot be performed then, you understand and agree that Pulp Strategy may delete any and all of your content within a commercially reasonable time and or on the expiration of the applicable trial period save the right to recover the fees payable, if any, by you under these terms and under the selected plans plus legal, banking and administrative expenses. <div class="space"></div>
  </div>
  <h3 class="term-head">9. PAYMENT PROCEDURE </h3>
  <div class="term-desc"> Once you choose a plan through the website, you will pay in advance the relevant fees as detailed in the plan. The payment shall be performed in accordance with the payment procedure set forth in the website, via credit/debit card, net banking, etc, or other means of payment as specified in the website or agreed with Pulp Strategy. If the relevant payment cannot be performed in advance, you understand and agree that Pulp Strategy may delete any of your content within a commercially reasonable time after the expiration of the due fees, save the right to recover the fees payable by You under these terms and under the selected plans plus legal, banking and administrative expenses.<div class="space"></div>
  </div>
  <h3 class="term-head">10. CHARGEBACK/CANCELATION/REFUND POLICY </h3>
  <div class="term-desc"> WE DO NOT HAVE A REFUND POLICY. If you terminate your plan’s subscription, before the expiry of the duration, then Pulp Strategy won’t be able to refund any fees of the same, it is understood and agreed that you have checked and utilised the free trial and you have accepted the terms and conditions and that you have been fully satisfied with the services before you opted / subscribed for the subscription base paid package / plan. If you dispute a credit card payment that is found to be invalid you will be permanently blacklisted and barred from use of the service. Any past due fees and costs will be sent to collections. If our collection efforts fail, unpaid debts will be reported to all available credit reporting agencies. Pulp Strategy has a zero tolerance policy for chargebacks and refunds. <div class="space"></div>
    The following are the steps of cancelation:<div class="space"></div>
    <ol>
    	<li>You may cancel your account at anytime by mailing via  intimating the cancellation on the website in the 'My Apps' section after logging in. </li>
   		<li>Once your account is cancelled all of your content will be immediately deleted from the service. </li>
    	<li>If you cancel the service post payment of the subscription at any point of the subscription period, Pulp Strategy will not refund any payment. </li>
    	<li>Upon expiration or effective termination of the service by either party for any reason, </li>
    
            <ul class="alphabet">
                <li>Pulp Strategy will cease to provide the service(s) on immediate effect, </li>
                <li>Your subscription period is over and you haven’t paid the next subscription prior to expiry, Pulp Strategy will cease to provide the service(s) on immediate effect on the day, date and time of the lapse / expiry of subscription term. </li>
            </ul>
    	<li>Pulp Strategy reserves the right to modify or terminate the Instappy.com service for any reason, without notice at any time. </li>
    	<li>Fraud: Without limiting any other remedies, Pulp Strategy may suspend or terminate your account if we suspect that you (by conviction, settlement, insurance or escrow investigation, or otherwise) have engaged in fraudulent activity in connection with the site and or for any of the following reasons </li>
            <ul class="alphabet">
                <li>If it is found that you have infringed on the content rights of any individual, party and or parties.</li>
                <li>If you have infringed on the IP rights or any other legal rights of any individual, party and or parties.</li>
                <li>If the content you post is found to be fake, illegal, inappropriate, contains fake claims, representations, banned under the law of the land, hurtful to any individual, party and or parties, or contains religious material which may be offensive to any religious sect, religion, party or individual.</li>
            </ul>
    	<li>Pulp Strategy reserves the right to modify or terminate the Instappy.com service if you are found to promote and or sell any banned material and or item under the law of the land. </li>
    </ol>
  </div>
  <h3 class="term-head">10. YOUR CONTENT</h3>
  <div class="term-desc">  You are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with such account. You must not describe or assign keywords to your network or application content in a misleading or unlawful manner, including in a manner intended to trade on the name or reputation of others, and Pulp Strategy may terminate the services of any user / subscriber if it contains, any description, content or keyword that Pulp Strategy considers inappropriate or unlawful, or otherwise likely to cause Pulp Strategy liability. You must immediately notify Pulp Strategy of any unauthorised uses of your dashboard, your mobile application, your account or any other breaches of security. Pulp Strategy will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. If you operate a social network, a community, operate a mobile application, publish content or post links, or otherwise make (or allow any third party to make) material available by means of the service or other services, you are entirely responsible for the content of, and any harm resulting from, your content. That is the case regardless of whether your content in question constitutes text, graphics, an audio file, or computer software. By making your content available, you represent and warrant that: the downloading, reading, viewing, copying and use of your content will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark or trade secret rights, of any third party; if your employer has rights to intellectual property you create, you have either
  <ul class="roman">
  	<li>received permission from your employer to post or make available your content, including but not limited to any software, or  </li>
    <li>secured from your employer a waiver as to all rights in or to your content; You have fully complied with any third-party licenses relating to your content, and have done all things necessary to successfully pass through to end users any required terms; You are responsible for maintaining and ensuring that you do not demo, display, sell and that your content is free of 
    	<ol>
       <li>adult goods and services which includes pornography and other sexually suggestive materials (including literature, imagery and other media); escort or prostitution services</li>
       <li>alcohol which includes alcohol or alcoholic beverages which include but are not limited to beer, liquor, wine, or champagne</li>
       <li>body parts which includes organs or other body parts </li>
       <li>bulk marketing tools which includes email lists, software, or other products enabling unsolicited email messages (spam) </li>
       <li>cable descramblers and black boxes which includes devices intended to obtain cable and satellite signals for free</li>
       <li>child pornography  which includes pornographic materials involving minors</li>
       <li>copyright unlocking devices which includes Mod chips or other devices designed to circumvent copyright protection </li>
       <li>copyrighted media which includes unauthorised copies of books, music, movies, and other licensed or protected materials </li>
       <li>copyrighted software which includes unauthorised copies of software, video games and other licensed or protected materials, including OEM or bundled software</li>
       <li>counterfeit and unauthorised goods which includes replicas or imitations of designer goods; items without a celebrity endorsement that would normally require such an association; fake autographs, counterfeit stamps, and other potentially unauthorised goods </li>
       <li>drugs and drug paraphernalia which includes illegal drugs and drug accessories, including herbal drugs like salvia and magic mushrooms </li>
       <li>drug test circumvention aids which includes drug cleansing shakes, urine test additives, and related items </li>
       <li>endangered species which includes plants, animals or other organisms (including product derivatives) in danger of extinction</li>
       <li>gaming/gambling which includes lottery tickets, sports bets, memberships/ enrollment in online gambling sites, and related content </li>
       <li>government IDs or documents which includes fake IDs, passports, diplomas, and noble titles</li>
       <li>hacking and cracking materials which includes manuals, how-to guides, information, or equipment enabling illegal access to software, servers, websites, or other protected property</li>
       <li>illegal goods which includes materials, products, or information promoting illegal goods or enabling illegal acts </li>
       <li>miracle cures which includes unsubstantiated cures, remedies or other items marketed as quick health fixes </li>
       <li>offensive goods which includes literature, products or other materials that: 
       	<ul class="alphabet">
        	<li>defame or slander any person or groups of people based on race, ethnicity, national origin, religion, sex, or other factors</li>
       		<li>encourage or incite violent acts</li>
       		<li>promote intolerance or hatred. </li>
        </ul>
       </li>
       <li>offensive goods, crime which includes crime scene photos or items, such as personal belongings, associated with criminals </li>
       <li>prescription drugs or herbal drugs or any kind of online pharmacies which includes drugs or other products requiring a prescription by a licensed medical practitioner</li>
       <li>pyrotechnic devices and hazardous materials which includes fireworks and related goods; toxic, flammable, and radioactive materials and substances </li>
       <li>regulated goods which includes air bags; batteries containing mercury; Freon or similar substances/refrigerants; chemical/industrial solvents; government uniforms; car titles; license plates; police badges and law enforcement equipment; lock-picking devices;  pesticides; postage meters; recalled items; slot machines; surveillance equipment; goods regulated by government of the land or other agency specifications</li>
       <li>securities which includes stocks, bonds, or related financial products</li>
       <li>tobacco and cigarettes which includes cigarettes, cigars, chewing tobacco, and related products</li>
       <li>traffic devices which includes radar detectors/jammers, license plate covers, traffic signal changers, and related products </li>
       <li>weapons (which cannot be sold unlicensed) which includes firearms, ammunition, knives, brass knuckles, gun parts, and other armaments </li>
       <li>wholesale currency which includes discounted currencies or currency exchanges </li>
       <li>live animals </li>
       <li>multi Level Marketing collection fees </li>
       <li>matrix sites or sites using a matrix scheme approach </li>
       <li>work-at-home information </li>
       <li>drop-shipped merchandise </li>
       <li>any books and or banned material which may have been announced as banned / restricted by the government from time to time temporarily or errantly.</li>
       <li>any product or service which is not in compliance with all applicable laws and regulations whether federal, state, local or international including the laws of India. </li>
   </ol>
   	</li>
  </ul>
  </div>
  <h3 class="term-head">11. REPRESENTATIONS AND WARRANTY OF THE SUBSCRIBER OR CUSTOMER</h3>
  <div class="term-desc"> You represent and warrant that
  	<ul class="alphabet">
    	<li>your use of the service will be in strict accordance with the Pulp Strategy Privacy Policy, Instappy privacy policy and with this agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and</li>
    	<li>your use of the service will not infringe or misappropriate the intellectual property rights of any third party. You acknowledge and agree that you may not and may not permit, assist or allow any third party to:
        	<ul class="roman">
            	<li>copy, reproduce, publish, transmit, distribute, upload, post, publicly display, encode, translate, modify or create derivative works from, sell, license or otherwise distribute any Pulp Strategy content, including but not limited to mirroring, framing or linking to any third party’s computer, server, website; </li>
      			<li>access or use this Website or any Pulp Strategy content for any commercial purposes, including any advertising or advertising revenue generating activity on your own or any third party’s website, platform or other online space or means; </li>
      			<li>use any automatic or manual process aimed at accessing, acquiring, copying or monitoring the website or the Pulp Strategy content or any part thereof, and/or in any way reproducing the structure or appearance of the Website or any Pulp Strategy content, or circumventing any copy-protection devices, obtaining or attempting to obtain any materials, documents or information made available through the website, for example by resorting to deep-links, page-scrapers, robots, spiders, or similar technologies; </li>
      			<li>access or attempt to access any portion, section or feature of the website, or any other systems or networks connected to the website or any of our servers to which you are not allowed to access, by resorting to hacking, password mining or any other illegitimate technologies or means; </li>
      			<li>probe, scan or test the vulnerability of the website or any other computer or network connected to the website; </li>
      			<li>breach the protection, security or authentication measures on the website or on the digital platform; </li>
	      		<li>reverse look-up, trace or seek to trace any information regarding any other user of or visitor to the website, or any other customer, or carry out any similar activity; </li>
      			<li>exploit or use the website, any Pulp Strategy content, or any service or information made available or offered by or through the website for any unlawful purposes or for any purposes not allowed by these website term of services or solicit the performance of any illegal activity or other activity which infringes the rights of Pulp Strategy or others; </li>
       			<li>take any action that imposes an unreasonably or disproportionately large load on the infrastructure of the website or of the digital platform, or any systems or networks connected to the website or to the digital platform; </li>
     			<li>use any device, software, mechanism or any other technology aimed at interfering or attempting to interfere with the proper working of the website or of the digital platform or any transaction being conducted on the website or on the digital platform, or with any other person’s use of the website. Pulp Strategy reserve the right to discontinue or suspend your access or use of the website or of the digital platform, without notice, if
                	<ul class="roman">
						<li>Pulp Strategy reasonably deem you have violated the these terms of services or </li>
     					<li>Pulp Strategy reasonably deem such a measure necessary for security reasons</li>
                    </ul>
                </li>
            </ul>
       </li>
    </ul>     
  </div>
  <h3 class="term-head"> 12. UPDATES, UPGRADES, RENEWAL </h3>
  <div class="term-desc"> Updates or upgrades of INSTAPPY.COM may be available to client/customer, if provided by Pulp Strategy as provided hereinabove. Nothing contained hereinabove bind Pulp Strategy to provide updates /upgrades of INSTAPPY.COM. <div class="space"></div>
    Within a period of 30 days prior to due expiry date of the subscription period, Pulp Strategy may electronically or otherwise intimate you and request you for its renewal. You may renew your license, at your sole discretion, pursuant the payment of the license fee as may be determined by the Pulp Strategy from time to time. If you does not chooses to renew your subscription within a period of 30 days prior to the due expiry date, this agreement shall be terminated automatically and consequence shall follow. <div class="space"></div>
  </div>
  <h3 class="term-head"> 13. THIRD PARTY ITEMS/PLATFORM </h3>
  <div class="term-desc"> INSTAPPY.COM may require you to register on any third party platform. You undertake to go through the terms & conditions of such third party platform before registering yourself and also to abide by those terms & conditions.  INSTAPPY.COM may also may allow you to access and interoperate with third party content, software applications, and data services, including rich internet applications (“third party items”). Your access to and use of any third party items, including any goods, services, or information, is governed by the terms and conditions respecting such offerings and copyright laws. Third party items are not owned or provided by Pulp Strategy. You agree that you will not use any of such third party items in violation of copyright laws. Pulp Strategy or the third party may at any time, for any reason, modify or discontinue the availability of any third party items. Pulp Strategy does not control, endorse, or accept responsibility for third party items. Any dealings between you and any third party in connection with a third party items, including such party’s privacy policies and use of your personal information, delivery of and payment for goods and services, and any other terms, conditions, warranties, or representations associated with such dealings are solely between you and such third party. third party items might not be available in all languages and Pulp Strategy or the third party may, at any time and for any reason, modify or discontinue the availability of any third party items. <div class="space"></div>
    EXCEPT AS EXPRESSLY AGREED BY PULP STRATEGY OR ITS AFFILIATES OR A THIRD PARTY IN A SEPARATE AGREEMENT, YOUR USE OF PULP STRATEGY AND THIRD PARTY OFFERINGS IS AT YOUR OWN RISK UNDER THE WARRANTY AND LIABILITY LIMITATIONS. <div class="space"></div>
  </div>
  <h3 class="term-head">14. ADDITIONAL LICENSING REQUIREMENTS AND/OR USE RIGHTS </h3>
  <div class="term-desc"> Third Party Programs: INSTAPPY.COM may include third party programs that Pulp Strategy, not the third party, licenses to you under this agreement. Notices, if any, for the third party program are included for your information only. <div class="space"></div>
    Media Elements: If there is any media element included with INSTAPPY.COM, you cannot:
    	<ul>
        	<li>sell, license or distribute copies of any media elements by themselves or as a product;</li>
            <li>grant your customers rights to further license or distribute the media elements;</li>
            <li>license or distribute for commercial purposes media elements; or</li>
            <li>create obscene or scandalous works using the media elements.</li>
        </ul>
    Advertising Elements or Ads: There are ads / advertisements panels / space which will be included in some subscription plans of the Instappy applications that you / users create under such plans. This is a part of the service and you may not remove, modify or tamper with such elements. These ads will be controlled by Instappy.com / Pulp Strategy and Pulp Strategy may chose to display any advertising content in this space as it may deem fit and are within the preview of the law.  You further are informed that if you / users will like to remove the ads from their applications as created by them on Instappy.com and are covered under the terms of this agreement and the terms of the Instappy.com service they will need to upgrade to a higher payment plan in which case the ads / space will be removed for the duration of the higher paid plan only. <div class="space"></div>
    Language Packs and Proofing Tools: If you acquire a language pack, language interface pack or proofing tool that offers additional language version support for INSTAPPY.COM, you may use the additional languages included in that pack or tool. The language packs, language interface packs and proofing tools are a part of INSTAPPY.COM and may not be used separately. <div class="space"></div>
    Additions and or modifications: If you need to have any changes made other than what is already provided in the service as is you are informed that any such additional customisation can only be made by Pulp Strategy / Instappy.com team. You cannot authorise or permit any unauthorised access for the purpose of modification or any other. Any such modification and or additional service will be provided at an additional cost which will need to be paid to Pulp Strategy / Instappy.com in advance prior to the start of such a service. <div class="space"></div>
    You will be responsible for keeping backup versions of the information and data provided by you. You will not expect the website/Pulp Strategy server to restore or keep back up of your information and data and not hold the website/Pulp Strategy accountable for any loss of data in any circumstances. <div class="space"></div>
  </div>
  <h3 class="term-head">15. DISCLAIMER</h3>
  <div class="term-desc"> Instappy.com  and other information are delivered to you “as is” and with all faults. To the maximum extent permitted under applicable law, except as expressly set out in this agreement, all conditions, endorsements, guarantees, representations, or warranties of any kind, express or implied, including without limitation, any conditions, endorsements, guarantees, representations or warranties of durability, fitness for a particular purpose or use, merchantability, merchantable quality, non-infringement, satisfactory quality, or title, or arising from a statute or custom or a course of dealing or usage of trade, and all other warranties, representations, conditions, endorsements or guarantees of any kind, either express or implied, are hereby disclaimed and excluded to the maximum extent permitted under applicable law. <div class="space"></div>
    Nothing in this agreement imply or create any continued right to use Instappy.com or other products after termination of this agreement. <div class="space"></div>
    Service(s): <div class="space"></div>
    <ul>
    	<li>Except to the extent specifically prohibited by applicable law, each service is provided or made accessible "as is" and "as available", without condition, endorsement, guarantee, representation or warranty of any kind by Pulp Strategy. </li>
    	<li>Pulp Strategy does not warrant or provide any other similar assurance whatsoever that uninterrupted use or operation of any service, continued availability of any service, or that any messages, content or information sent by or to you will be accurate, transmitted in uncorrupted form or within a reasonable period of time. </li>
    </ul>
    third party items and third party services, linked sites: <div class="space"></div>
    <ul>
    	<li>Except to the extent specifically prohibited by applicable law, the third party services and third party items are not under the control of Pulp Strategy, Pulp Strategy does not endorse any particular third party items or third party services, and Pulp Strategy has no responsibility whatsoever for your selection, use, access, or implementation of the third party services or third party items. </li>
    	<li>The foregoing applies regardless of: 
        	<ul class="alphabet">
            	<li>how you acquire or obtain access to third party items and/or third party services;</li>
                <li>whether any such third party items or third party services are required in order to use all or any portion of Instappy.com; or</li>
                <li>you acquire or gain access to such third party items and third party services by way of the handheld product, including without limitation, via a browser or app world software, or by way of links to specific third party software or third party websites   and/or other third party services made available to you by icons or bookmarks on your handheld product, or by any other means whatsoever, including without limitation on other websites or through information accessed using your handheld product. </li>
            </ul>
        </li>
    	<li>Without limiting the foregoing, except to the extent specifically prohibited by applicable law, all third party items and third party services used by you in conjunction with Instappy.com, on an "as is" and "as available" basis, without any condition, endorsement, guarantee, representation or warranty of any kind, and Pulp Strategy hall have no liability whatsoever to you or any third party claiming by or through you, for any issue relating to the   third party items, or third party services, including, without limitation: 
        	<ul class="alphabet">
            	<li>the accuracy, transmission, timeliness or continued availability of such third party items, or third party services, or  of any portion of the software that is designed solely to enable such access;</li>
                <li>the performance or non-performance of the third party items, or third party services; or</li>
                <li>the interoperability of the third party items, or the third party services with all or a portion of Instappy.com. </li>
            </ul>
        </li>
    	<li>Without limiting the foregoing, except to the extent specifically prohibited by applicable law, you specifically agree Pulp Strategy is not responsible or liable for, any viruses, or any threatening, defamatory, obscene, tortious, offensive or illegal third party services, third party items or for any third party items or third party services or the transmission thereof, that infringe any third party intellectual property rights.  Your recourse in the event of any such claim with respect to any third party items, or third party services, shall be solely against the relevant third parties. </li>
    </ul>
  </div>
  <h3 class="term-head">16. Additional Disclaimers</h3>
  <div class="term-desc"> Pulp Strategy, in no event shall be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising (in any manner whatsoever, including but not limited to negligence) out of or in connection with the website/use of software. Pulp Strategy aggregate liability in all circumstance is limited to the amount of charges/ fees, if any, paid by you to it. <div class="space"></div>
    Pulp Strategy associates, affiliates and service providers and technology partners make no representations or warranties about the accuracy, reliability, completeness, and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the website or that the operation of the website or the use and operation of the software or gateway partner will be error free and/or uninterrupted. Pulp Strategy provides no guarantee to its users in respect of the products sold on the website or for the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the website or any delay, failure, interruption or errors in the operation of the website or the software or gateway partner or for other services. <div class="space"></div>
  </div>
  <h3 class="term-head">17. INDEMNITY</h3>
  <div class="term-desc"> You shall indemnify and hold harmless Pulp Strategy its parent, subsidiaries, affiliates, third-parties and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of your breach of this including policies incorporated herein by reference, or your violation of any law, rules or regulations or the third party’s policy, terms & conditions. <div class="space"></div>
  </div>
  <h3 class="term-head">18. PROCESS /TRANSACTION </h3>
  <div class="term-desc"> Pulp Strategy neither makes any representations nor makes any warranties regarding the amount of time needed to complete processing, including delays in the banking system and nor shall Pulp Strategy be liable for any actual or consequential damages arising from any claim of delay. <div class="space"></div>
  </div>
  <h3 class="term-head">19. PRIVACY AND COLLECTION OF PERSONAL INFORMATION. </h3>
  <div class="term-desc"> The personal information / data including but not limited to the information provided by the you to the website during the course of a transaction shall be treated as strictly confidential and retained in accordance with the Privacy Policy which is incorporated herein by reference and applicable laws and regulations including but not limited to Information Technology Act, 2000 and rules there under. <div class="space"></div>
    By using the website and/or by providing your information, you consent to the collection and use of such information disclosed by you on the website by Pulp Strategy. Pulp Strategy does not sell or rent or otherwise disclose your personal information to third parties for their marketing purposes without your explicit consent and Pulp Strategy only uses your information in the manner described in the Privacy Policy. If you do not agree to your Information being transferred or used in this way please do not use the website. <div class="space"></div>
    The website/INSTAPPY.COM, support or service subscription employs applications and tools to collect user’s information, materials etc. (which may include identifiable, sensitive or non –public information or other information). By entering into this agreement, or using INSTAPPY.COM, support or service subscription, you and users agree to this Privacy Policy and to the collection, processing, copying, backup, storage, transfer and use of this data by Pulp Strategy. You are solely responsible for securing any privacy-related rights and permissions from your users as may be required by local law or by your internal policies. This privacy policy is in furtherance of the privacy policy displayed on the website for its use. <div class="space"></div>
  </div>
  <h3 class="term-head">20. BREACH</h3>
  <div class="term-desc"> Pulp Strategy may at its sole discretion, without limiting other remedies it may have in law and equity, take such action as it deems fit including but not limited to cancellation of the transaction or payments made, limit your activity, forthwith temporarily/indefinitely suspend or terminate or block your subscription/license/ membership, and/or refuse to provide you with access to the website, use of software or initiate any legal action it may deem fit, particularly in the event: <div class="space"></div>
    <ul>
    	<li>You breach any of the provisions of these terms including any of the policies, documents, terms and conditions made there under which are incorporated therein by reference; </li>
    	<li>Pulp Strategy is unable to verify or authenticate any information provided by you; </li>
    	<li>Pulp Strategy believes that your actions may cause legal liability to Pulp Strategy, other users or yourself. </li>
    </ul>
    No actions, omissions or decisions taken by Pulp Strategy shall waive any rights or claims that Pulp Strategy may have against the user. <div class="space"></div>
    When you are suspended or blocked, you shall not register or attempt to register with the website or use the website or attempt to use or use INSTAPPY.COM in any manner whatsoever until such time that you are reinstated for such use. Reinstatement shall be at the sole discretion of Pulp Strategy. <div class="space"></div>
    You shall have no claim of any nature whatever against Pulp Strategy, in case Pulp Strategy exercises its right under this clause. If you may any kind of claim, such claim shall be deemed non-existence or non-maintainable. <div class="space"></div>
  </div>
  <h3 class="term-head">21. TRANSACTION /PAYMENT</h3>
  <div class="term-desc"> You agree that: <div class="space"></div>
  	<ul>
    	<li>Pulp Strategy shall have right to limit the amount payable and volume of transaction that may be conducted on single valid card/valid bank account by a user and may refuse to process transaction(s) exceeding such limit and may also block certain valid cards or valid bank accounts that are suspected to be misused while paying the transaction price. </li>
    	<li>To prevent any misuse, a payment (in whichever method) of the transaction price initiated by the buyer may be flagged or kept on hold for additional checks and verification in which case Pulp Strategy may contact the buyer for verification of or additional information, details, data and documents. Pulp Strategy may not confirm the payment if such information, details, data and documents are false, misleading, incorrect or incomplete and consequently the valid card and/or the valid bank account will not be charged. In such case, the downloading /delivery will not commence until payment confirmation. The result of the checks and verification may be to the user. </li>
    	<li>Pulp Strategy  shall have right to refuse to process transaction price in respect of transactions by user/subscriber with a prior history of questionable charges including without limitation breach of any agreements by buyer with Pulp Strategy or breach/ violation of any applicable law or any charges imposed by the issuing bank. </li>
    	<li>All transactions conducted on the website for which valid cards and valid bank accounts are used for remittance of payment for transactions will also be governed by the terms and conditions agreed to between the user and the respective issuing bank and payment instrument issuing company and the terms agreed between Pulp Strategy and payment gateway provider, as applicable and you shall not violate any such terms and conditions. You agree to indemnify and hold harmless Pulp Strategy and its service providers against any direct or indirect liability that may arise on account of such violation. </li>
    </ul>
  </div>
  <h3 class="term-head">22. INTELLECTUAL PROPERTY OWNERSHIP, RESERVATION OF RIGHTS.</h3>
  <div class="term-desc"> INSTAPPY.COM, documentation and related information provided to you by Pulp Strategy are the intellectual property of Pulp Strategy. The structure, organisation, and code of INSTAPPY.COM are the valuable intellectually property (e.g. trade secrets and confidential information) of Pulp Strategy. INSTAPPY.COM is protected by law, including without limitation the copyright laws of India and other countries, and by international treaty provisions. <div class="space"></div>
    Neither you nor your authorised users acquire hereby any ownership right, title or interest in or to any intellectual property or other proprietary rights, including patents, designs, trademarks, copyright, database rights or rights in any confidential information or trade-secrets, in or relating to INSTAPPY.COM or any part thereof.  You also do not acquire any license rights in or related to INSTAPPY.COM or any portion thereof, other than the rights expressly licensed to you under this agreement or in another mutually agreed upon written agreement that you may have with Pulp Strategy.  No title and/or any right of possession to the Pulp Strategy Product(s) (if any) is granted by virtue of this agreement.  Any rights not expressly granted herein are expressly reserved.  For clarity, notwithstanding anything else in this agreement, in no event shall the licenses granted in INSTAPPY.COM herein extend, or be construed to extend, to the use of any Third Party Services or Third Party Items either on a standalone basis or in conjunction with INSTAPPY.COM, and, without limiting the foregoing, in no event shall the licenses granted hereunder be construed such that any supplier of such Third Party Services or Third Party Items be able to successfully assert that use of such Third Party Services or Third Party Items either in conjunction with all or a part of INSTAPPY.COM or on a standalone basis are licensed under Pulp Strategy patents by virtue of the fact that INSTAPPY.COM is licensed hereunder.  There are severe penalties, both civil and criminal, for intellectual property infringement. You agree that nothing in this agreement shall adversely affect any rights and recourse to any remedies, including, without limitation, to injunctive relief, that Pulp Strategy may have under any applicable laws relating to the protection of Pulp Strategy intellectual property or other proprietary rights. <div class="space"></div>
  </div>
  <h3 class="term-head">23. CONNECTIVITY AND PRIVACY. </h3>
  <div class="term-desc"> You acknowledge and agree to the following: <div class="space"></div>
  	<ul class="roman">
    	<li>When you use INSTAPPY.COM your may connect to the Pulp Strategy server operated by Pulp Strategy, or other third party. Your Internet Protocol Address (“IP Address”) is sent when this happens. The Pulp Strategy server or the other third party may use technology to send (or “serve”) advertising or other electronic content that appears in or near the opened file in software. The third party may also use JavaScript, web beacons (also known as action tags or single-pixel gifs), and other technologies to increase and measure the effectiveness of advertisements and to personalise advertising content. Your communication with such third party or third party websites is governed by the third party’s privacy policy. Pulp Strategy may not have access to or control over features that a third party may use, and the information practices of third party or its websites are not covered by the Pulp Strategy Privacy Policy. </li>
    	<li>If your device is connected to the internet, INSTAPPY.COM may, without additional notice, check for updates that are available for download and installation to your device. Such updates may be downloaded subject to other terms and will be installed with additional notice, if any. The use of such information, including your IP Address, as provided by the update process is governed by the Pulp Strategy Privacy Policy. </li>
    	<li>INSTAPPY.COM may allow third parties to store your certain information. The type and amount of information that the third party application requests to be stored can vary by application and such requests are controlled by the third party. </li>
    	<li>If your device is connected to the Internet, INSTAPPY.COM may, without additional notice and on an intermittent or regular basis, facilitate your access to content and services that are hosted and maintained by Pulp Strategy or its affiliates (“Pulp Strategy Services”). Pulp Strategy reserves the right to begin charging a fee for access to or use of Pulp Strategy Service that was previously offered at no charge. If your device is connected to the internet, the software may, without additional notice, update downloadable materials from these services so as to provide immediate availability of these Pulp Strategy Services even when you are offline. When the software connects to the internet as a function of a Pulp Strategy, your IP Address, user name, and password may be sent to Pulp Strategy servers and stored by Pulp Strategy in accordance with the additional terms of use or the “help” menu in the software. This information may be used by Pulp Strategy to send you transactional messages to facilitate the Pulp Strategy Service. Whenever INSTAPPY.COM makes an internet connection and communicates with Pulp Strategy server, whether automatically or due to explicit user request, the Pulp Strategy Privacy Policy shall apply. Please note that the Pulp Strategy Privacy Policy allows tracking of your website visits, software use in detail and use of cookies, web beacons, and similar devices. </li>
    </ul>
  </div>
  <h3 class="term-head">24. CONFIDENTIALITY AND NO REVERSE ENGINEERING. </h3>
  <div class="term-desc"> You acknowledge and agree that INSTAPPY.COM was:
  <ul class="alphabet">
  	<li>developed at considerable time and expense by Pulp Strategy. This agreement gives you no right to obtain from Pulp Strategy or its distributors any source code for INSTAPPY.COM, and, except to the extent that Pulp Strategy is expressly precluded by law from prohibiting these activities, You agree that neither you nor your authorised users will alter, modify, adapt, create derivative works, translate, deface, or reverse engineer INSTAPPY.COM, or attempt to do so, or permit, acquiesce, authorise or encourage any other party to do the same.  For the purpose of this agreement, "Reverse Engineer" includes any act of reverse engineering, translating, disassembling, decompiling, decrypting or deconstructing (including any aspect of "dumping of RAM/ROM or persistent storage", "cable or wireless link sniffing", or "black box" reverse engineering) data, software (including interfaces, protocols, and any other data included in or used in conjunction with programs that may or may not technically be considered software code), service, or hardware or any method or process of obtaining or converting any information, data or software from one form into a human-readable form. </li>
  </ul>
  <h3 class="term-head">25. TERM & TERMINATION</h3>
  <div class="term-desc"> This agreement shall be effective upon your agreeing to be bound by the terms of this agreement (as described in the preamble above) and shall continue in effect unless terminated in accordance with the provisions set out herein. <div class="space"></div>
    Remedies and termination for default. <div class="space"></div>
    <ul class="alphabet">
    	<li>If you or your authorised users breach this agreement, Pulp Strategy may, in addition to all other rights and remedies provided by this agreement or by law, immediately terminate this agreement and any other license agreement between you and Pulp; and/or cease to provide any service(s) to you or your authorised users in relation to INSTAPPY.COM.  Where you have provided Pulp Strategy with accurate contact information, Pulp Strategy shall provide you with notice of termination. </li>
    	<li>Without limiting the generality of the foregoing sentence, You will be deemed to be in breach of this agreement and Pulp Strategy will have the right to terminate this agreement upon providing notice if:
			<ul class="roman">
            	<li>You or your authorised users fail to comply with or perform a term or condition herein; </li>
    			<li>You materially contravene any other license agreement or terms of service that you may have with Pulp Strategy for any portion of services used by you or your authorised users, including, without limitation, the terms of any agreement that you have agreed to on a Pulp Strategy website or otherwise; </li>
    			<li>You or any of your authorised users interfere with Pulp Strategy customer service or business operations; or </li>
    			<li>Any periodic fees or costs associated with your use of INSTAPPY.COM are not paid on or before expiry of its period. </li>
             </ul>
         </li>
    	<li>In addition, Pulp Strategy may terminate this agreement and/or immediately cease to provide the service(s) without any liability whatsoever to you or your authorised users if Pulp Strategy is prevented from providing any portion or all of any service by any law, regulation, requirement or ruling issued in any form whatsoever by judicial or other governmental body, or if a notice from a government agency or department indicates that Pulp Strategy is not permitted to provide any portion or all of the services. </li>
    	<li>Nothing herein shall be construed to require Pulp Strategy to seek a waiver of any such law, rule, regulation, or restriction, or seek judicial review or appeal of any court order.  Pulp Strategy shall not have any liability to you or your authorised users arising from or related to the termination of this agreement in accordance with this section. </li>
    </ul>
    Effect of Termination.  Upon termination of this agreement, however caused, or if your subscription or a free trial for INSTAPPY.COM expires: 
    <ul class="alphabet">
    	<li>You will immediately discontinue all use of INSTAPPY.COM (or item of INSTAPPY.COM for which the license has expired) and return all copies of INSTAPPY.COM that are in your and/or your authorised users' possession or control; and</li>
        <li>Pulp Strategy shall have the right to block any transmission of data to and from INSTAPPY.COM, without notice to you.  Upon termination of any account you may have with Pulp Strategy, You authorise Pulp Strategy to delete any files, programs, data and email messages associated with such account, without notice to you.  In the event of the termination of this agreement by Pulp Strategy pursuant to provisions of this agreement, you shall pay to Pulp Strategy all fees (including reasonable lawyers' fees and costs) and related expenses expended or incurred by Pulp Strategy in the enforcement of its rights hereunder. </li>
    </ul>
    The certain provisions of this agreement which is intended to be survived the termination of this agreement shall survive the termination, cancellation or expiration of this agreement for any reason. <div class="space"></div>
  </div>
  <h3 class="term-head">26. FORCE MAJEURE </h3>
  <div class="term-desc"> "Event of Force Majeure" means an event beyond Pulp Strategy control or the third party service provider, which prevents Pulp Strategy or such third party from complying with any of its obligations under this contract, including but not limited to: <div class="space"></div>
  	<ul class="roman">
 		<li>act of God (such as, but not limited to, fires, explosions, earthquakes, drought, tidal waves and floods);</li>
    	<li>war, hostilities (whether war be declared or not), invasion, act of foreign enemies, mobilisation, requisition, or embargo;</li>
    	<li>rebellion, revolution, insurrection, or military or usurped power, or civil war;</li>
    	<li>contamination by radio-activity from any nuclear fuel, or from any nuclear waste from the combustion of nuclear fuel, radio-active toxic explosive, or other hazardous properties of any explosive nuclear assembly or nuclear component of such assembly;</li>
    	<li>riot, commotion, strikes, go slows, lock outs or disorder, unless solely restricted to employees of the supplier or of his subcontractors; or</li>
    	<li>acts or threats of terrorism.</li>
    </ul>
    Neither Pulp Strategy nor the third party service provider shall be considered in breach of this contract to the extent that performance of their respective obligations is prevented by an Event of Force Majeure. <div class="space"></div>
  </div>
  <h3 class="term-head">27. EXPORT RULES</h3>
  <div class="term-desc"> You agree that INSTAPPY.COM will not be shipped, transferred, or exported into any country or used in any manner prohibited by export laws, restrictions, or regulations (collectively the “Export Laws”). In addition, if INSTAPPY.COM is identified as export controlled items under the export laws, you represent and warrant that you are not a citizen, or otherwise located within, an embargoed nation (including without limitation Iran, Syria, Sudan, Cuba, and North Korea) and that you are not otherwise prohibited under the export laws from receiving INSTAPPY.COM. All rights to Use the Software are granted on condition that such rights are forfeited if you fail to comply with the terms of this agreement.<div class="space"></div>
  </div>
  <h3 class="term-head">28. GOVERNING LAW</h3>
  <div class="term-desc"> This agreement will be governed by and construed in accordance with the substantive laws in force in the Republic of India. The courts at Delhi shall have exclusive jurisdiction over all disputes relating to this agreement. Any dispute arising out of or in connection with this agreement, including any question regarding its existence, validity, or termination, shall be referred to and finally resolved by arbitration in Delhi in accordance with the provisions of (Indian) Arbitration & Conciliation Act, 1996 or any statutory modification or replacement thereof. There shall be one arbitrator, selected by Pulp Strategy. The language of the arbitration shall be English. Notwithstanding any provision in this agreement, Pulp Strategy or you may request any judicial, administrative, or other authority to order any provisional or conservatory measure, including injunctive relief, specific performance, or other equitable relief, prior to the institution of legal or arbitration proceedings, or during the proceedings, for the preservation of its rights and interests or to enforce specific terms that are suitable for provisional remedies. The English version of this agreement will be the version used when interpreting or construing this agreement. This agreement will not be governed by the conflict of law rules of any jurisdiction, the application of which is expressly excluded.<div class="space"></div>
  </div>
  <h3 class="term-head">29. GRIEVANCE REDRESSAL/DISPUTE RESOLUTION</h3>
  <div class="term-desc"> You agree that in case of any grievance, objections, complaint, dispute differences, whether it relates to use of website (including suspension, termination or blocking of your membership and right to use), other users, content of website, privacy, order, delivery, payment, and product or anything or circumstances relating to aforesaid or others or in connection with the validity, interpretation, implementation or alleged breach of any provision of the user agreement or other agreement, the same shall be resolved as per the following procedure: <div class="space"></div>
  <ul class="roman">
    <li>You shall address your grievance to designated grievance officers via the website in the section of my apps post logging in, and provide him/her all necessary information/documents to enable him/her to resolve the issues. The link details grievance cell is mentioned in the Privacy Policy; </li>
    <li>If your grievance/dispute/differences are not resolved within a period of 30 days from the date of lodging of complaint or such other period as may be deemed necessary by the grievance officer, the same shall be referred to conciliation of a conciliation officer appointed by the Pulp Strategy, which shall be conciliated at Delhi. You may participate in conciliation through mail exchange, telephone, fax, or other electronic medium. </li>
    <li>If the aforesaid conciliation fails, the dispute/differences shall be referred to the sole arbitrator appointed by the Pulp Strategy, which arbitrator shall not be employee of the Pulp Strategy. The sole arbitrator shall conduct the arbitration proceeding as per the provisions of [Indian] Arbitration & Conciliation Act, 1996 or any statutory modification or enactment thereof. The place of arbitration shall be at Delhi and language used English. The award passed by the sole arbitrator shall be final and binding upon you as well as Pulp Strategy </li>
  </ul>
  </div>
  <h3 class="term-head">30. GENERAL PROVISIONS.</h3>
  <div class="term-desc"> If any part of this agreement is found void and unenforceable, it will not affect the validity of the balance of this agreement, which shall remain valid and enforceable according to its terms. This agreement may only be modified by a writing signed by an authorised officer of Pulp Strategy. Updates may be licensed to you by Pulp Strategy with additional or different terms. This is the entire agreement between Pulp Strategy and you relating to the use of website/downloading source/software and it supersedes any prior representations, discussions, undertakings, communications, or advertising relating to the software. <div class="space"></div>
    Except as explicitly stated otherwise, any notices directed to Pulp Strategy are Instappy shall be given by email to legal@instappy.com and any notices to you by Pulp Strategy shall be provided to the email address provided by you during the registration process. Notice shall be deemed given 48 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, we may give you notice by registered mail, postage prepaid and return receipt requested, to the address provided to us during the registration process. In such case, notice shall be deemed given 10 days after the date of mailing. <div class="space"></div>
    Pulp Strategy at its sole discretion shall be entitled to assign or transfer its rights and obligations under this agreement hereunder to any other person without your prior consent <div class="space"></div>
    All remedies of Pulp Strategy under this agreement whether provided herein or conferred by statute, civil law, common law, custom or trade usage, are cumulative and not alternative and may be enforced successively or concurrently. <div class="space"></div>
    This user agreement, or privacy policy, and other related information published on website has been published in accordance with rules of Information Technology (Intermediaries guidelines) Rules, 2011. <div class="space"></div>
    No party to this agreement shall be deemed to have waived any of its rights, powers or remedies under this agreement unless such waiver is expressly set forth in a writing signed by the waiving party. No written waiver of any provision of this agreement shall be deemed to be, or shall constitute,
    <ul class="roman">
    	<li>a waiver of any other provision of this agreement, whether or not similar, or</li>
        <li>a continuing or subsequent waiver of the same or another provision of this agreement. The failure of either party to enforce at any time any of the provisions of this agreement, or the failure to require at any time performance by the other party of any of the provisions of this agreement, will in no way be construed to be a present or future waiver of any such provisions, or in any way affect the validity of either party to enforce each and every such provision thereafter. </li>
    </ul>
    The captions and headings of sections and subsections contained in this agreement are provided for convenience of reference only and shall not be considered a part hereof for purposes of interpreting this agreement, and, way the meaning or intent of this agreement or any of its terms or provisions. <div class="space"></div>
    This electronic record is generated by a computer system and does not require any physical or digital signatures. <div class="space"></div>
    This agreement is binding, on the use of service in full or in part thereof. <div class="space"></div>
  </div>
</div>
</div>
<?php require_once('website_footer.php');?>
